package com.example.gara_management.constant;

public interface ErrorCode {

  String UNKNOWN = "UNKNOWN";
  String INVALID_TOKEN = "INVALID_TOKEN";
  String ACCESS_DENIED = "ACCESS_DENIED";
  String BAD_CREDENTIALS = "BAD_CREDENTIALS";
  String UNAUTHORIZED = "UNAUTHORIZED";
  String EXPIRED_TOKEN = "EXPIRED_TOKEN";
  String MISSING_PARAMETER = "MISSING_PARAMETER";
  String INVALID_INPUT_DATA = "INVALID_INPUT_DATA";
  String HTTP_REQUEST_METHOD_NOT_SUPPORTED = "HTTP_REQUEST_METHOD_NOT_SUPPORTED";
  String NO_HANDLER_FOUND = "NO_HANDLER_FOUND";
  String ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND";
  String ENTITY_WAS_DELETED = "ENTITY_WAS_DELETED";
  String USER_NOT_FOUND = "USER_NOT_FOUND";
  String USER_NOT_ACTIVE = "USER_NOT_ACTIVE";
  String USERNAME_EXISTED = "USERNAME_EXISTED";
  String PASSWORD_NOT_CHANGED = "PASSWORD_NOT_CHANGED";
  String OLD_PASSWORD_INCORRECT = "OLD_PASSWORD_INCORRECT";

  String ENTITY_EXISTED = "ENTITY_EXISTED";

}
